<?php

namespace Dupriez\ProductBundle\Repository;

/**
 * LivresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivresRepository extends \Doctrine\ORM\EntityRepository
{
}
