<?php

namespace Dupriez\ProductBundle\Repository;

/**
 * LivresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivresRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLivreWithProduct()
    {
        $qb =$this->createQueryBuilder('l')
            ->Join('l.products','products')
            ->addSelect('products');

        return $qb->getQuery()->getResult();
    }

}
