<?php

namespace Dupriez\ProductBundle\Repository;

/**
 * PC_portableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PC_portableRepository extends \Doctrine\ORM\EntityRepository
{
}
