<?php

namespace Dupriez\ProductBundle\Repository;

/**
 * telephoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class telephoneRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTelephoneWithProduct()
    {
        $qb =$this->createQueryBuilder('t')
            ->Join('t.products','products')
            ->addSelect('products');

        return $qb->getQuery()->getResult();
    }
}
