<?php

namespace Dupriez\ProductBundle\Repository;

/**
 * VetementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VetementsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getVetementWithProduct()
    {
        $qb =$this->createQueryBuilder('v')
            ->Join('v.products','products')
            ->addSelect('products');

        return $qb->getQuery()->getResult();
    }
}
