<?php

namespace Dupriez\CommandeBundle\Repository;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductViewPanier()
    {
        $qb=$this
            ->createQueryBuilder('p')
            ->join('p.products','product_id')
            ->addSelect('products');

        return $qb->getQuery()->getResult();
    }
}
