<?php

namespace Dupriez\CommandeBundle\Repository;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPanierUser($user)
    {
        $qb = $this
            ->createQueryBuilder('p')
            ->where('p.user = :user and p.etat = :etat')
            ->setParameter('user', $user)
            ->setParameter('etat', 0)
            ->select('p');

        return $qb->getQuery()->getResult();
    }

}
